import {Post} from "@/store/postStore";
import {Comment} from "@/store/commentStore";
import {User} from "@/store/userStore";

export const mockPosts: Post[] = [
    {
        id: "POST-001",
        title: "Help debugging pointers in CSE 13S",
        description:
            "I'm stuck on a segmentation fault in my linked list assignment. Looking for someone to review my code and help me understand memory allocation.",
        category: "tutoring",
        subject: "computer science",
        tags: ["C", "pointers", "linked list"],
        userId: "U001",
        userName: "Ivan Argueta",
        createdAt: new Date("2025-11-01T10:30:00Z").toISOString(),
        updatedAt: new Date("2025-11-01T11:00:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 5,
    },
    {
        id: "POST-002",
        title: "Essay feedback needed for WRIT 2",
        description:
            "Could someone review my essay draft on digital media and attention spans? Mainly need help with structure and transitions.",
        category: "review",
        subject: "writing",
        tags: ["essay", "feedback", "writing"],
        userId: "U002",
        userName: "Samantha Lee",
        createdAt: new Date("2025-11-02T14:15:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 7,
    },
    {
        id: "POST-003",
        title: "Math 19A — Need help with derivatives",
        description:
            "Trying to understand chain rule and implicit differentiation before the midterm. Anyone free to tutor this weekend?",
        category: "tutoring",
        subject: "math",
        tags: ["calculus", "derivatives", "chain rule"],
        userId: "U003",
        userName: "Carlos Ramirez",
        createdAt: new Date("2025-11-02T18:45:00Z").toISOString(),
        postStatus: "IN_PROGRESS",
        replies: 0,
        likes: 4,
    },
    {
        id: "POST-004",
        title: "Looking for feedback on art portfolio",
        description:
            "I’m preparing my digital art submission for the UCSC showcase. Would love a peer review on composition and lighting.",
        category: "feedback",
        subject: "art",
        tags: ["digital art", "portfolio", "critique"],
        userId: "U004",
        userName: "Maya Chen",
        createdAt: new Date("2025-11-03T09:10:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 2,
    },
    {
        id: "POST-005",
        title: "Study group for Physics 6B",
        description: "Looking to form a small study group for upcoming topics on electric fields and Gauss's Law. Hoping to meet twice a week on campus.",
        category: "tutoring",
        subject: "physics",
        tags: ["physics", "study group", "6B"],
        userId: "U005",
        userName: "Jordan Patel",
        createdAt: new Date("2025-11-03T15:20:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 1,
        likes: 3,
    },
    {
        id: "POST-006",
        title: "Help with CS project Git issues",
        description:
            "My group is having merge conflicts and I think our Git workflow is messed up. Can someone explain branching best practices?",
        category: "tutoring",
        subject: "computer science",
        tags: ["git", "version control", "group project"],
        userId: "U006",
        userName: "Emily Johnson",
        createdAt: new Date("2025-11-04T12:05:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 2,
        likes: 6,
    },
    {
        id: "POST-007",
        title: "Advice on internship applications",
        description:
            "Applying to tech internships for the first time and feeling overwhelmed. Should I focus on personal projects or resume polish?",
        category: "career",
        subject: "career development",
        tags: ["internships", "resume", "career advice"],
        userId: "U007",
        userName: "Derek Nguyen",
        createdAt: new Date("2025-11-04T17:50:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 8,
    },
    {
        id: "POST-008",
        title: "WRIT 1 — Peer review trade",
        description:
            "I can review your WRIT essay if you review mine. Looking for honest critique on clarity and flow.",
        category: "review",
        subject: "writing",
        tags: ["peer review", "essay", "trade"],
        userId: "U008",
        userName: "Alex Torres",
        createdAt: new Date("2025-11-05T09:25:00Z").toISOString(),
        postStatus: "IN_PROGRESS",
        replies: 3,
        likes: 1,
    },
    {
        id: "POST-009",
        title: "Need help understanding recursion",
        description:
            "My brain just shuts down when I think about functions calling themselves. Could someone walk me through some simple examples?",
        category: "tutoring",
        subject: "computer science",
        tags: ["recursion", "C", "functions"],
        userId: "U009",
        userName: "Noah Kim",
        createdAt: new Date("2025-11-06T11:40:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 1,
        likes: 5,
    },
    {
        id: "POST-010",
        title: "Looking to join an astronomy club group",
        description:
            "Does anyone attend the rooftop telescope nights? Want to learn constellations and basic telescope setup.",
        category: "meetup",
        subject: "astronomy",
        tags: ["astronomy", "telescope", "club"],
        userId: "U010",
        userName: "Riley Morgan",
        createdAt: new Date("2025-11-06T21:00:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 4,
    },
    {
        id: "POST-011",
        title: "Need help running ANOVA test for research project",
        description:
            "Working on a psychology research paper and need help running an ANOVA test in R. I have the dataset ready, just confused about the statistical interpretation.",
        category: "tutoring",
        subject: "other",
        tags: ["stats", "R", "ANOVA"],
        userId: "U011",
        userName: "Hannah Brooks",
        createdAt: new Date("2025-11-07T08:45:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 0,
        likes: 3,
    },
    {
        id: "POST-012",
        title: "Looking for lab partner for BIO 20L",
        description:
            "Need a reliable partner who can meet consistently. I’m good with note-taking and data organization.",
        category: "meetup",
        subject: "science",
        tags: ["bio lab", "partner", "20L"],
        userId: "U012",
        userName: "Marcus Hill",
        createdAt: new Date("2025-11-07T11:12:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 2,
        likes: 1,
    },
    {
        id: "POST-013",
        title: "Advice on building a personal portfolio website",
        description:
            "Trying to build a simple developer portfolio using React but the layout looks boring. Any suggestions or template recommendations?",
        category: "feedback",
        subject: "computer science",
        tags: ["react", "portfolio", "frontend"],
        userId: "U013",
        userName: "Javier Gomez",
        createdAt: new Date("2025-11-08T13:30:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 4,
        likes: 9,
    },
    {
        id: "POST-014",
        title: "WRIT 2 — Struggling to form a thesis statement",
        description:
            "My arguments feel disconnected and my thesis feels weak. Could someone help me rework my main claim?",
        category: "tutoring",
        subject: "writing",
        tags: ["writ 2", "thesis", "essay help"],
        userId: "U014",
        userName: "Sarah Kim",
        createdAt: new Date("2025-11-09T09:55:00Z").toISOString(),
        postStatus: "IN_PROGRESS",
        replies: 0,
        likes: 5,
    },
    {
        id: "POST-015",
        title: "Learning Japanese — practice buddy?",
        description:
            "Currently studying Japanese 1. Would like someone to practice hiragana and simple conversation with once or twice a week.",
        category: "meetup",
        subject: "other",
        tags: ["japanese", "study buddy", "hiragana"],
        userId: "U015",
        userName: "Rei Sato",
        createdAt: new Date("2025-11-09T18:05:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 3,
        likes: 7,
    },
    {
        id: "POST-016",
        title: "Looking for critique on short story draft",
        description:
            "It's a 3-page short story for my literature class. Mainly looking for feedback on pacing and emotional tone.",
        category: "review",
        subject: "writing",
        tags: ["creative writing", "short story", "editing"],
        userId: "U016",
        userName: "Eleanor Davis",
        createdAt: new Date("2025-11-10T10:15:00Z").toISOString(),
        postStatus: "OPEN",
        replies: 1,
        likes: 4,
    },

];
//////////////////////////////////////////////////////////////////////////////////////////
export const mockComments: Record<string, Comment[]> = {
    "POST-001": [
        {
            id: "C-1",
            postId: "POST-001",
            parentId: null,
            userId: "U010",
            userName: "Alex",
            text: "Can you share a minimal repro?",
            createdAt: new Date("2025-11-01T11:10:00Z").toISOString(),
            likes: 1,
        },
        {
            id: "C-2",
            postId: "POST-001",
            parentId: "C-1",
            userId: "U001",
            userName: "Ivan Argueta",
            text: "Yep, pushing now—thanks!",
            createdAt: new Date("2025-11-01T11:15:00Z").toISOString(),
            likes: 0,
        },
    ],
};
/////////////////////////////////////////////////////////////////////////////////////////
export const mockUsers: User[] = [
    {
        id: "0",
        name: { firstName: "Test", lastName: "User" },
        userFields: {
            email: "user@gmail.com",
            password: "password",
            confirmPassword: "password",
            address: {
                street: "123 Test St",
                city: "Test City",
                state: "CA",
                zip: "00000",
            },
        },
        status: "ACTIVE",
        profileImageUrl: "",
    },
    {
        id: '1',
        name: { firstName: "Ivan", lastName: "Argueta" },
        userFields: {
            email: "iargueta@ucsc.edu",
            password: "password123",
            confirmPassword: "password123",
            address: { street: "1156 High St", city: "Santa Cruz", state: "CA", zip: "95064" },
        },
        status: "ACTIVE",
        profileImageUrl: "https://i.pravatar.cc/150?img=11",
    },
    {
        id: '2',
        name: { firstName: "Maya", lastName: "Chen" },
        userFields: {
            email: "mchen7@ucsc.edu",
            password: "hunter2!!",
            confirmPassword: "hunter2!!",
            address: { street: "100 Bay St", city: "Santa Cruz", state: "CA", zip: "95060" },
        },

        status: "PENDING",
        profileImageUrl: "https://i.pravatar.cc/150?img=12",
    },
    {
        id: '3',
        name: { firstName: "Diego", lastName: "Ramirez" },
        userFields: {
            email: "dramirez@ucsc.edu",
            password: "scslug2025",
            confirmPassword: "scslug2025",
            address: { street: "44 Seabright Ave", city: "Santa Cruz", state: "CA", zip: "95062" },
        },
        status: "ACTIVE",
        profileImageUrl: "https://i.pravatar.cc/150?img=13",
    },
    {
        id: '4',
        name: { firstName: "Aisha", lastName: "Khan" },
        userFields: {
            email: "aikhan@ucsc.edu",
            password: "liftStrong!",
            confirmPassword: "liftStrong!",
            address: { street: "200 Laurel St", city: "Santa Cruz", state: "CA", zip: "95060" },
        },
        status: "SUSPENDED",
        profileImageUrl: "https://i.pravatar.cc/150?img=14",
    },
    {
        id: '5',
        name: { firstName: "Noah", lastName: "Patel" },
        userFields: {
            email: "npatel@ucsc.edu",
            password: "gym-time",
            confirmPassword: "gym-time",
            address: { street: "5 Mission St", city: "Santa Cruz", state: "CA", zip: "95060" },
        },
        status: "INACTIVE",
        profileImageUrl: "https://i.pravatar.cc/150?img=15",
    },
    {
        id: '6',
        name: { firstName: "Sofia", lastName: "Lopez" },
        userFields: {
            email: "slopez9@ucsc.edu",
            password: "bananaSlug!",
            confirmPassword: "bananaSlug!",
            address: { street: "500 River St", city: "Santa Cruz", state: "CA", zip: "95060" },
        },
        status: "ACTIVE",
        profileImageUrl: "https://i.pravatar.cc/150?img=16",
    },
    {
        id: '7',
        name: { firstName: "Ethan", lastName: "Nguyen" },
        userFields: {
            email: "enguyen3@ucsc.edu",
            password: "pushpulllegs",
            confirmPassword: "pushpulllegs",
            address: { street: "888 Pacific Ave", city: "Santa Cruz", state: "CA", zip: "95060" },
        },
        status: "PENDING",
        profileImageUrl: "https://i.pravatar.cc/150?img=17",
    },
    {
        id: '8',
        name: { firstName: "Lena", lastName: "Hernandez" },
        userFields: {
            email: "lhernandez@ucsc.edu",
            password: "cardioDays",
            confirmPassword: "cardioDays",
            address: { street: "120 Ocean St", city: "Santa Cruz", state: "CA", zip: "95060" },
        },
        status: "ACTIVE",
        profileImageUrl: "https://i.pravatar.cc/150?img=18",
    },
];
/////////////////////////////////////////////////////////////////////////////////////////